### PR TITLE
Breaking: Add createLambdaHandler

### PR DESCRIPTION
**Pull request by wholesomedev**
This PR upgrades clown and config, and adds back the `createLambdaHandler` to use in `assign-env` so that I can upgrade to the latest there.

### CODE REVIEW

**Comment by forabi** [comment]
We'll also need to restore Node 6.10 Babel config as Lambda @ Edge is still on 6.

**Comment by wholesomedev** [comment]
@forabi I'm assuming that Node 6 is not needed here. 

As long as the Node version in `assign-env` itself is 6, then this code (when it's bundled in `assign-env`) will get transpiled further to Node 6.

**Comment by forabi** [comment]
> As long as the Node version in assign-env itself is 6, then this code (when it's bundled in assign-env) will get transpiled further to Node 6.

We do not transpile `node_modules` in webpack. We explicitly ignore the pattern `/node_modules/` when transpiling with `babel-loader`. This package should use the lowest Node.js version that's needed by _any_ of the dependants.

**Comment by wholesomedev** [comment]
It seems to me that it would make more sense if dependents transpiled the
code to make it the way they need.

**Comment by forabi** [comment]
> It seems to me that it would make more sense if dependents transpiled the code to make it the way they need.

Yeah, but this is usually avoided because it could take a long time with large `node_modules` and many packages may have already been transpiled/minified and re-transpiling them will cause large/ugly output.

**Comment by forabi** [comment]
Also, for Node.js apps, `node_modules` is usually not touched at all, and `webpack-node-externals` is used instead of bundling the entire dependency tree with webpack. This saves a lot of build time. `lambda-assign-env` is an exception to this rule though, because we can't go over 1 MB with Lambda@Edge so we can't just bundle `node_modules` and push the package. We may get away with transpiling `node_modules` :smile:

**Comment by wholesomedev** [comment]
>Also, for Node.js apps, `node_modules` is usually not touched at all, and `webpack-node-externals` is used instead of bundling the entire dependency tree with webpack. This saves a lot of build time. `lambda-assign-env` is an exception to this rule though, because we can't go over 1 MB with Lambda@Edge so we can't just bundle `node_modules` and push the package. We may get away with transpiling `node_modules` :smile: 

That's interesting. Whenever I've used webpack with Node apps, I've bundled the whole thing indiscriminately. If bundling is good enough for the web, it should be good enough for my Node app (which is usually a CLI). That's usually my line of thinking.

But anyway, since this will work for the Lambda@Edge for now, we can keep it the way it is. If for whatever reason, that doesn't work, we can degrade this to an earlier Node version.

**Pull request merged**
